### ISSUE TITLE
S7 - As a user, I want to be able to assign a task to myself or a different user, in order to put someone in charge of it.  

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#102]
**Acceptance Criteria**
- [x] While creating or editing a task, the user can select one assigne from a list of all registered users
- [x] The task appears in the assigned users personal task list

**Development Tasks**
- [x] sopra-fs22-group-26/server#177
- [x] sopra-fs22-group-26/server#178
- [x] sopra-fs22-group-26/client#111
- [x] sopra-fs22-group-26/client#112
- [x] sopra-fs22-group-26/client#115
