### ISSUE TITLE
S8 - As a user I want to be able to assign a reporter to the task, in order to have someone monitoring my progress. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#105]
**Acceptance Criteria**
- [x] While creating or editing a task, the user can select one reporter from a list of all registered users.
- [x] The task appears in the reporter’s list of tasks to report.

**Development Tasks**
- [x] sopra-fs22-group-26/client#63
- [x] sopra-fs22-group-26/client#104
- [x] sopra-fs22-group-26/client#103
- [x] #166
- [x] #182
