### ISSUE TITLE
S9 - As a user, I want to have a system where you get awarded points for having finished a task, in order to motivate myself and the other team members. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#108]
**Acceptance Criteria**
- [x] When the assignee has finished a task, it will be marked as finished in the reporter’s list.
- [x] The reporter can assess the finished task and award points to the user who has finished it.
- [x] The user can see their reward points on the personal profile page.
- [x] The reward should reflect the difficulty or importance of a task.

**Development Tasks**
- [x] sopra-fs22-group-26/client#64
- [x] sopra-fs22-group-26/client#65
- [x] sopra-fs22-group-26/client#66
- [x] sopra-fs22-group-26/client#132
- [x] sopra-fs22-group-26/client#131
- [x] sopra-fs22-group-26/client#129
- [x] sopra-fs22-group-26/client#130
- [x] sopra-fs22-group-26/server#218
- [x] sopra-fs22-group-26/client#133
