### ISSUE TITLE
S10 - As a user, I want to have a scoreboard where I can see a clear comparison of gained award points between me and other colleagues, in order to have a competition element.

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#113]
**Acceptance Criteria**
- [x] The user can navigate to a scoreboard where they can see a list of all team members and their award points.

**Development Task**
- [x] sopra-fs22-group-26/client#67
- [x] sopra-fs22-group-26/client#99
- [x] sopra-fs22-group-26/client#68
