### ISSUE TITLE
S11 - As a user, I want to be able to add comments to a task, in order to clearly specify what has to be done or to have discussions with other team members. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#116]
**Acceptance Criteria**

- [x] Upon editing a task, the user sees a text field where they can enter comments.
- [x] Upon saving a comment, the comment is added to the list of recent comments.
- [x] If a user clicks on the “delete” button of their own comment, the comment is removed.
- [x] The user can see all previously submitted comments.

**Development Tasks**
- [x] sopra-fs22-group-26/client#69
- [x] sopra-fs22-group-26/client#70
- [x] sopra-fs22-group-26/server#119
- [x] sopra-fs22-group-26/client#71
- [x] #196
- [x] #234
