### ISSUE TITLE
S12 - As a user, I want to be able to initiate an “Estimate Poll” session with other users, in order to estimate the time needed to complete a task. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#121]
**Acceptance Criteria**
- [x] The user can click on an “Estimate Poll” button to start the session.
- [x] Upon starting, the user can invite other members by selecting them on a user list.
- [x] When a team member is invited to the session, they are notified by a message on the dashboard.
- [x] Upon notification, a user can accept or reject the invitation.
- [x] Upon accepting the invitation, the user enters the “Estimate Poll” area.

**Development Tasks**
- [x] sopra-fs22-group-26/client#73
- [x] sopra-fs22-group-26/client#72
- [x] sopra-fs22-group-26/client#74
- [x] sopra-fs22-group-26/client#75
- [x] sopra-fs22-group-26/client#76
- [x] sopra-fs22-group-26/client#159
- [x] sopra-fs22-group-26/client#157
- [x] sopra-fs22-group-26/client#160
- [x] sopra-fs22-group-26/server#188
- [x] sopra-fs22-group-26/server#189
