### ISSUE TITLE
S13 - As a user, I want to be able to take part in an “Estimate Poll” session to give my estimate on a task. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#127]
**Acceptance Criteria**
- [x] The organizing user can start the game by clicking on the start button.
- [x] The users can enter a number between 1 and a threshold set by the organizing user, representing the time estimate of the task anonymously.
- [x] Upon finishing the voting, the average of all submitted estimates updates the estimate of the task.
- [x] The organizing user can end the session, upon which the widget is no longer available to any user.

**Development Task**
- [x] sopra-fs22-group-26/client#120
- [x] sopra-fs22-group-26/client#121
- [x] sopra-fs22-group-26/client#77
- [x] sopra-fs22-group-26/client#79
- [x] sopra-fs22-group-26/client#78
- [x] sopra-fs22-group-26/client#158
- [x] sopra-fs22-group-26/client#161
- [x] sopra-fs22-group-26/client#162
- [x] sopra-fs22-group-26/client#163
- [x] sopra-fs22-group-26/client#194
- [x] sopra-fs22-group-26/server#146
- [x] sopra-fs22-group-26/server#190
- [x] sopra-fs22-group-26/server#191
- [x] sopra-fs22-group-26/server#236
- [x] sopra-fs22-group-26/server#237
- [x] sopra-fs22-group-26/server#238
- [x] sopra-fs22-group-26/server#192
- [x] sopra-fs22-group-26/server#193
- [x] sopra-fs22-group-26/server#240
- [x] sopra-fs22-group-26/server#261
- [x] sopra-fs22-group-26/client#202
