### ISSUE TITLE
S14 - As a user, I want to see upcoming public holidays while creating or editing a task, in order to not schedule the task for inconvenient dates. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#131]
**Acceptance Criteria**
- [x] When the user enters the date information for a task, they can perceive upcoming public holidays, which are provided by an external API.
- [x] If the selected due date of a task falls on a holiday, the system alerts the user.

**Development Tasks**
- [x] sopra-fs22-group-26/client#80
- [x] sopra-fs22-group-26/client#81
- [x] sopra-fs22-group-26/client#146
