### ISSUE TITLE
S16 - As a user, I want to see an overview of tasks assigned to me, and I want to be able to sort them by due date or priority, in order not to miss important or upcoming tasks. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#137]
**Acceptance Criteria**
- [x] The user clicks on the “My tasks” button and sees all tasks assigned to them.
- [x] The user can select “sort by due date”, “sort by creation date” or “sort by priority” and the tasks are ordered accordingly.
- [x] The user can see the total time estimate of all their tasks for a given week.

**Development Tasks**
- [x] sopra-fs22-group-26/client#105
- [x] sopra-fs22-group-26/client#83
- [x] sopra-fs22-group-26/client#84
- [x] sopra-fs22-group-26/client#106
- [x] sopra-fs22-group-26/client#85
- [x] sopra-fs22-group-26/server#170
- [x] #201
