### ISSUE TITLE
S1 - As a user I want to sign up with a unique username and a password, to gain access to services and information that are only available to registered users. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#76]
**Acceptance Criteria**
- [x] The user can click on a signup button that directs them to a signup page.
- [x] The user can set their preferred user credentials in a signup form. User credentials are username, and password.
- [x] If the username is unique and the password matches the prerequisites, the user is registered with the corresponding user credentials and an additional user id, creation-date and user token.
- [x] If the username and password do not match the prerequisites, the request is denied.

**Development Tasks**
- [x] sopra-fs22-group-26/client#49
- [x] sopra-fs22-group-26/client#45
- [x] sopra-fs22-group-26/server#77
- [x] sopra-fs22-group-26/server#149
- [x] #164

**Comment by nmantzanas** [comment]
@wchang1011 @catinthecradle @jdhekh @hobinrani 

Please use the request body scheme as you find it in the example below:

<img width="329" alt="Screenshot 2022-04-04 at 16 45 44" src="https://user-images.githubusercontent.com/58571573/161570537-24d2c438-9ba2-43f7-957a-fc3f8db8dd9f.png">
