### ISSUE TITLE
S2 - As a registered user, I want to log in and log out, to gain access to user services. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#79]
**Acceptance Criteria**
- [x] A registered user can log in to the application and gain access to the services and information that is available to the user.
- [x] A logged in user can log out from the system.
- [x] User status is updated in the server.

**Development Tasks**
- [x] sopra-fs22-group-26/client#51
- [x] sopra-fs22-group-26/client#50
- [x] sopra-fs22-group-26/server#82
- [x] #161
- [x] sopra-fs22-group-26/client#97
