### ISSUE TITLE
S4 - As a user, I want to be able to recover my password in a save way, so that I will not suffer from production down-time due to being locked out of the system in case I have forgotten my password. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#88]
**Acctepance Criteria**
- [ ] A user can click on "I forgot my password" on the login page to receive a new, temporary password.
- [ ] Upon clicking the button, an e-mail is sent to the provided e-mail address of this user.
- [ ] The e-mail contains a link that leads the user to a password reset page.
- [ ] The link is valid for a short period of time only.

**Development Tasks**
- [x] sopra-fs22-group-26/client#55
- [x] sopra-fs22-group-26/server#90
- [x] sopra-fs22-group-26/client#56
- [x] sopra-fs22-group-26/server#92

**Comment by catinthecradle** [comment]
Should we skip this user story and mention it in the report as a possible extension for the future?

**Comment by catinthecradle** [comment]
Could be implemented in a further update.
