### ISSUE TITLE
S5 - As a user, I want to create a new task, enter a title and description and assign a due date and priority (i.e. none, low, medium, high) to it, in order to add the task to the task list. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#93]
**Acceptance criteria**
- [x] User clicks on "create new task" and can fill in the desired information.
- [x] User can select the task priority from a predefined set.
- [x] After filling in the information, the user can save the task and is redirected to the task overview page.
- [x] The newly created task appears in the task lists.

**Development tasks**
- [x] sopra-fs22-group-26/server#96
- [x] sopra-fs22-group-26/client#57
- [x] sopra-fs22-group-26/client#58
- [x] sopra-fs22-group-26/client#59
- [x] sopra-fs22-group-26/client#100
- [x] sopra-fs22-group-26/client#108
- [x] sopra-fs22-group-26/client#109
