### ISSUE TITLE
S6 - As a user, I want to be able to change or delete existing tasks, in order to adjust them according to circumstances. 

### ISSUE THREAD

**Issue by nmantzanas** [sopra-fs22-group-26/server#98]
**Acceptance Criteria**
- [ ] User clicks on a task and can edit all the task’s parameters (title, description, due date, priority).
- [ ] After having saved, the user is redirected to the task overview page and the task shows the changed data.
- [ ] After having deleted, the user is redirected to the task overview page and the task is removed.

**Development Tasks**
- [x] sopra-fs22-group-26/server#153
- [x] sopra-fs22-group-26/client#94
- [x] sopra-fs22-group-26/client#60
- [x] sopra-fs22-group-26/client#95
- [x] sopra-fs22-group-26/client#96
- [x] sopra-fs22-group-26/server#101
